name: CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4 
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest isort flake8 Flake8-pyproject git+https://github.com/psf/black build twine
    - name: Lint
      run: |
        isort .
        black .
        flake8 ./x12 ./tests
    - name: Test
      run: |
        pytest .
    - name: Build
      run: |
        python -m build
        twine check dist/*
